
files = [ "bus_access.v",
        "sprites.v",
        "sinewave.v",
        "border.v",
        "testpattern.v",
        "lightpen.v",
        "lumareg.v",
        "cycles.v",
        "matrix.v",
        "comp_sync.v",
        "vicii.v",
        "registers.v",
        "raster.v",
        "serration.v",
        "equalization.v",
        "pixel_sequencer.v",
        "addressgen_efinix.v",
        "hires_pixel_sequencer.v",
        "hires_addressgen.v",
        "hires_dvi_sync.v",
        "hires_vga_sync.v",
        "colorreg.v",
        "hires_matrix.v",
        "hires_vga_sync.v",
        "divide.v",
        "videoram_efinix.v",
]
